#!/usr/bin/env python
# encoding: utf-8

import sys
import argparse
import importlib
import rapid.systems

# print rapid.systems.__all__
METRO_SYSTEM = 'TaipeiMetro'  # 'TaichungMetro'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('depart')
    parser.add_argument('arrive')
    parser.add_argument('--limit', type=int, help='列出筆數', default=5,  required=False)
    args = parser.parse_args()

    depart = args.depart
    arrive = args.arrive
    lines = args.limit
    transfer = args.max_transfer

    mod = importlib.import_module('rapid.systems.' + METRO_SYSTEM)
    metro = getattr(mod, METRO_SYSTEM)()
    metro.search_routes(depart, arrive, lines)
