#!/usr/bin/env python
# encoding: utf-8

import sys
import importlib
import rapid.systems

# print rapid.systems.__all__
METRO_SYSTEM = 'TaipeiMetro'  # 'TaichungMetro'

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usege:")
        print("%s DEPARTURE ARRIVAL [lines]" % sys.argv[0])
    else:
        depart = sys.argv[1]
        arrive = sys.argv[2]
        lines = int(sys.argv[3]) if len(sys.argv) >= 4 else 5

        mod = importlib.import_module('rapid.systems.' + METRO_SYSTEM)
        metro = getattr(mod, METRO_SYSTEM)()
        metro.search_routes(depart, arrive, lines)
